### ISSUE TITLE
Locale errors

### ISSUE THREAD

**Issue by gustavs-gutmanis** [rlanvin/php-rrule#10]
Hi @rlanvin,

Seems like it's impossible to use the `RRule::humanReadable()` method if the `\Locale` doesn't exist, or if the locale is wrong. There are some cases where the default `Locale` is `en_US_POSIX` which in turn triggers an exception in `RRule::i18nLoad()` line `2022`. Would it be possible to fallback to `en` if the locale isn't set or isn't supported?

I could make a PR for it if you'd like, just wondering if that's something you see as fitting in this case?

**Comment by rlanvin** [comment]
Hi,

Sure, a PR is always appreciated, so if you feel like it feel free. Here are my comments:

* `Locale` is part of the `intl` extension. I had intended this extension to be optional, so it definitely should not fail if `intl` is not loaded... I suggest you get the locale from the old fashioned `setlocale()` method when `intl` is not loaded.
* I didn't know that `en_US_POSIX` was a valid locale, so yes, the regexp in line 2022 should probably be updated. I think it some cases the old `setlocale()` can also return strange locales like `C` I think, so keep that in mind.
* Having a fallback locale if the locale is not set for some reason a good idea, though I think `Locale` or `setlocale` will always return *something*.
* Having a fallback locale if the locale doesn't exist is also a good idea, but I'm wondering if hardcoding `en` is a good idea. Maybe this could be an option of `humanReadable` (with `en` as default, so I can select another fallback language if necessary, and `null` or `false` meaning "no fallback, throw an exception if you can't find the locale")

Also, please remember to add (or update) a test that demonstrate the bugs in the PR. You should also update the CHANGELOG file.

**Comment by gustavs-gutmanis** [comment]
Ok, thanks for the input - very good points.
I'll update the tests, but I wonder how could I test `Locale` class not existing.

**Comment by gustavs-gutmanis** [comment]
I have a question - what should happen if there is no translation file for a given locale?
Right now it throws an exception saying that it couldn't load translations for said locale.
Maybe it should try to use the $fallbackLocale, if any were to be given?

**Comment by rlanvin** [comment]
Fixed by PR #11
