### ISSUE TITLE
Sorting byminute and byhour breaks bysetpos logic

### ISSUE THREAD

**Issue by Temzasse** [rlanvin/php-rrule#101]
Hi and thanks for this great library 👋🏻 

I think I might have found a bug.

Let's say we are building an app where we want to create a rrule to describe that an event should happen every day at 10:30 and 16:00. If I have understood rrule correctly we have to use `byhour` and `byminute` in conjunction with `bysetpos` to pick the correct indices of all the generated occurrences so that only 10:30 and 16:00 are left. This would look something like this:

- `byhour=[10,16]`
- `byminute=[30,0]`
- `bysetpos=[1,4]`

The `bysetpos` value comes from the fact that rrule generates four combinations from `byhour` and `byminute`:  `[10:30, 10:00, 16:30, 16:00]` from which we want to pick the first and the last items (hence `bysetpos=[1,4]`).

Now in [here](https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L493) and [here](https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L475) the `byhour` and `byminute` lists are sorted which causes the `bysetpos` indices to not match anymore resulting in wrong times.

Is there some specific reason for sorting `byhour` and `byminute` arrays?

Thanks in advance! 🙂

**Comment by rlanvin** [comment]
Hello @Temzasse 
Apologies for the very late answer, for some reason I didn't receive a notification when you opened your ticket.
I hope this answer is still relevant nevertheless.

> Is there some specific reason for sorting byhour and byminute arrays?

Yes, while strictly speaking this isn't explicitly stated in the RFC, there is an expectation that the occurrences are returned **chronologically**. So in your example, without the bysetpos, you should get 4 occurrences:

1. 10:00
2. 10:30
3. 16:00
4. 16:30

If you want 10:30 and 16:00, your bysetpos should be 2,3, not 1,4.

If that doesn't work, please provide some code example so I can attempt to reproduce the bug (and indicate the version of the library you are using).

Thank you!
