### ISSUE TITLE
"IntlDateFormatter::create() failed. Error Code: 1 "datefmt_create: no such time zone: 'ATLANTIC/AZORES': U_ILLEGAL_ARGUMENT_ERROR" (this should not happen, please open a bug report!)".

### ISSUE THREAD

**Issue by jdbargy** [rlanvin/php-rrule#105]
`Version used: v2.3.0`

Hi, related to this [issue https://github.com/rlanvin/php-rrule/issues/103](https://github.com/rlanvin/php-rrule/issues/103 ) the uppercase of TimeZone specified in `DTSTART` is done by `createFromRfcString`.
Question is, how to avoid the exception throw by `humanReadable` when we use RRule generated by `createFromRfcString` ?

**Comment by rlanvin** [comment]
Hello, I just noticed your message in the other ticket now, not sure why I didn't get a notification when you initially commented... Let's continue the conversation there.
