### ISSUE TITLE
getNextOccurance

### ISSUE THREAD

**Issue by cubecleveland** [rlanvin/php-rrule#111]
This is not an issue but was wondering what woudl be the method to get the next available occurance from RRULE ?

**Comment by rlanvin** [comment]
It depends - how do you define "the next available occurrence"?

**Comment by cubecleveland** [comment]
Thanks for your response...

I ended up using the getOccurancesAfter() function, with the includive to true and limit to 1...

**Comment by rlanvin** [comment]
Yes that works. 👍 If you don't need inclusive, you can also use `getNthOccurrenceAfter`
