### ISSUE TITLE
Grammar problem in German translation

### ISSUE THREAD

**Issue by Chamaeleon-** [rlanvin/php-rrule#112]
We have a problem with the grammar of the translation of for example "Every 3 months the third Wednesday": 

Correct in German is "Alle 3 Monate der dritte Mittwoch des Monats" but it translates to "Alle 3 Monate der dritte Mittwoch**s** des Monats" ("mittwochs" is the adverb of "Mittwoch" / thursday).

A possible "workaround" would be to change [line 73](https://github.com/rlanvin/php-rrule/blob/master/src/i18n/de.php#L73) to "am" (German for "on") and all the weekdays from adverb form to noun to keep `byweekday` and `nth_weekday` sound.

Do you have preferences or suggestions on this topic?

**Comment by rlanvin** [comment]
Hey, thanks for the report. Are you sure we shouldn't also change the `nth_weekday` and `-nth_weekday` too? Does "am der erste Montag" work, or should it be "am ersten Montag"?

Also would you be happy to submit a pull request for this change?

**Comment by Chamaeleon-** [comment]
you're right, I didn't realize `byweekday` is used in front of `nth_weekday` too... "am der erste Montag" doesn't make sense...

I will have a look and play around a bit with the combinations to submit a PR 👍

**Comment by rlanvin** [comment]
Great thanks! Looking forward to your PR. You can use the script in the `bin` folder to test the result when you play around, for example ` ./bin/review_translations.php --locale de`
