### ISSUE TITLE
addExRule not working for me

### ISSUE THREAD

**Issue by edu27** [rlanvin/php-rrule#118]
Hi,

I'm having some trouble trying to exclude weekends.
This is my code:
```

$rrule = new RSet('RRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20220930T080000Z', new \DateTime($eDB->start_date));

$rrule->addExRule([
        'FREQ' => 'WEEKLY',
        'BYDAY' => 'SU,SA',
        'DTSTART' => '20220901T080000Z',
    ]);

$resultArray = $rrule->getOccurrences(); 
// also tried with getOccurrencesBetween and foreach ($rrule as $date) resultset, same luck
```

And this is the result. As you can see weekends are included.

> Thu, 01 Sep 2022 08:00:00 +0200  
> Fri, 02 Sep 2022 08:00:00 +0200  
> Sat, 03 Sep 2022 08:00:00 +0200  
> Sun, 04 Sep 2022 08:00:00 +0200  
> Mon, 05 Sep 2022 08:00:00 +0200  
> Tue, 06 Sep 2022 08:00:00 +0200  
> Wed, 07 Sep 2022 08:00:00 +0200  
> Thu, 08 Sep 2022 08:00:00 +0200  
> Fri, 09 Sep 2022 08:00:00 +0200  
> Sat, 10 Sep 2022 08:00:00 +0200  
> Sun, 11 Sep 2022 08:00:00 +0200  
> Mon, 12 Sep 2022 08:00:00 +0200  
> Tue, 13 Sep 2022 08:00:00 +0200  
> Wed, 14 Sep 2022 08:00:00 +0200  
> Thu, 15 Sep 2022 08:00:00 +0200  
> Fri, 16 Sep 2022 08:00:00 +0200  
> Sat, 17 Sep 2022 08:00:00 +0200  
> Sun, 18 Sep 2022 08:00:00 +0200  
> Mon, 19 Sep 2022 08:00:00 +0200  
> Tue, 20 Sep 2022 08:00:00 +0200  
> Wed, 21 Sep 2022 08:00:00 +0200  
> Thu, 22 Sep 2022 08:00:00 +0200  
> Fri, 23 Sep 2022 08:00:00 +0200  
> Sat, 24 Sep 2022 08:00:00 +0200  
> Sun, 25 Sep 2022 08:00:00 +0200  
> Mon, 26 Sep 2022 08:00:00 +0200  
> Tue, 27 Sep 2022 08:00:00 +0200  
> Wed, 28 Sep 2022 08:00:00 +0200  
> Thu, 29 Sep 2022 08:00:00 +0200  
> Fri, 30 Sep 2022 08:00:00 +0200 

What I'm doing wrong. Please, some help would be great.

Thanks,
Edu.

**Comment by rlanvin** [comment]
Well reading the code, my guess is that you have a timezone issue. You are creating exclusions (EXRULE) using UTC time as a start time (your DTSTART is `20220901T080000Z`), but your rule is apparently in UTC+2.

So the EXRULE says "exclude Sat, 03 Sep 2022 08:00:00 UTC" but that's not an occurrence. Your occurrence is "Sat, 03 Sep 2022 08:00:00 +0200" which is "Sat, 03 Sep 2022 06:00:00 UTC". So there is nothing to exclude.

**Comment by edu27** [comment]
Hello again!

I've tried converting from my current timezone to UTC, but still having same results:

```
$rrule = new RSet('RRULE:'.$eDB->recurrence_pattern, date_create($eDB->start_date, $dateTimezone)->setTimeZone(new \DateTimeZone('UTC'))); 
$rrule->addExRule([
        'FREQ' => 'WEEKLY',
        'BYDAY' => 'SU,SA',
    'DTSTART' => $startDate->setTimeZone(new \DateTimeZone('UTC')),
    ]);
```

> EXRULE DTSTART: {"date":"2022-09-25 22:00:00.000000","timezone_type":3,"timezone":"UTC"}  
> Sat, 01 Oct 2022 06:00:00 +0000  
> Sun, 02 Oct 2022 06:00:00 +0000  
> Mon, 03 Oct 2022 06:00:00 +0000  
> Tue, 04 Oct 2022 06:00:00 +0000  
> Wed, 05 Oct 2022 06:00:00 +0000

Thanks for your time!

**Comment by rlanvin** [comment]
So again, just reading your code here, your EXRULE generates occurrences at 22:00 UTC, while your RRULE generates occurrences at 06:00 UTC. It's the same problem, the time component is not matching, so there is nothing to exclude. You don't _need_ to use UTC (or even the same timezone for that matter), you only need the EXRULE to generate occurrences that match occurrences you want excluded. So why don't you simply use the same start date for both rules?

**Comment by edu27** [comment]
I thought the DTSTART was a range, from where it was to be aplying the exclusion.
Now I have it working. Thank you very much!
