### ISSUE TITLE
Question: Performance optimization when calculating occurrences using multiple rules

### ISSUE THREAD

**Issue by drubb** [rlanvin/php-rrule#126]
Hey @rlanvin,

thanks for this great library, it makes dealing with recurrency so much easier!

One question regarding performance:

Let's say there's a pretty large number of e.g. events, and each of them has one or multiple recurrence rules, like 'each sunday at 16pm' or 'every month on the second monday at 10am'. What would be the fasted way to calculate instances of all events in a given time interval, like a day or a week?

**Comment by rlanvin** [comment]
Hello,

Thanks, I'm glad you like it!

The solution at the library level is pretty straightforward: for events that have multiple recurrence rules, you can use a `RSet` object to combine the rules, and then use [`getOccurrencesBetween()`](https://github.com/rlanvin/php-rrule/wiki/RRuleInterface#getoccurrencesbetweenbegin-end-limit) to get the occurrences in the time interval. You would have to do that for each event, but if you just want the occurrences and don't need to identify which event they belong too, you could also just make one big `RSet` object (though I doubt this is your use case).

From a performance perspective, there isn't much the library can do. You should look at your macro architecture. For example if this is a operation that you have to do frequently (e.g. to display them on a web page or something) but the rules don't change that much, then you should pre-compute and cache the occurrences asynchronously, and only recalculate them when the rules change (again, asynchronously). So displaying the list would always be super fast and wouldn't require any calculation.

**Comment by drubb** [comment]
Thanks for your fast response!

I remember having tried the 'big' ruleset in the past, and it was consuming loads of memory, so I went back to calculating every rule separatly. But rulesets per event might work, I'll give it a try.

I'm for now caching and invalidating the HTML output (it's a Drupal application), but yes, I could add another caching layer just for the calculated instances. Good point, I'll think about it.

Best regards,
Boris

**Comment by rlanvin** [comment]
Depending on what you want to do, it might be worth it to even store the calculated instances in a database (or in some form of structured cache), so you can filter them when you want to retrieve them.

Feel free to close the ticket if I answered your question.
