### ISSUE TITLE
exRule and addRule conflict

### ISSUE THREAD

**Issue by philharmonie** [rlanvin/php-rrule#127]
I am using rrule to plan employees presences on different locations.
If a user is present from 10am - 11am every 2nd day on a specific location (I store the location's id) and I want to delete one specific day, I add an exDate for that.
But if I now add a presence for that slot on a different location, it will not show up, because there is an exdate for that time.

Is there I chance to include the location_id somehow, so that the exdate only excludes dates, that match a given location_id?

This is basically what I am doing:
```
foreach ($presences as $presence) {
            $rset = new RSet();
            $rset->addRRule($presence->toRrule());

            // Remove Blocked
            $userBlocked = $blocked[$presence->user->id] ?? [];
            foreach ($userBlocked as $block) {
                $rset->addExDate($block->start->addHour());
            }
}
```

**Comment by rlanvin** [comment]
I'm not sure I fully understand what you're trying to achieve. The library works with recurring dates only, the notion of "location" is something that you seem to have added on top of the lib for your own use case, so I don't think I can help. Here are some quick thoughts:

From the code snippet you added, it looks to me that the check you want to do (i.e. _"only excludes dates, that match a given `location_id`"_) should be done in your code before you call `addExDate`.

Or maybe you should have 2 RSets (one per location)?

Or maybe call `removeExDate` when you encounter the "_presence for that slot on a different location"_?

**Comment by philharmonie** [comment]
I store the presence like this:
```
array:12 [
  "id" => 66
  "user_id" => 2
  "location_id" => 11
  "start" => "2022-12-19T09:00:00.000000Z"
  "end" => "2025-12-31T11:00:00.000000Z"
  "frequency" => "WEEKLY"
  "interval" => 1
  "allDay" => false
  "days" => "2"
]
```
This is the presence of user 2 at location 11.
When I now add an exrule for `2022-12-19 10:00:00 - 2022-12-19 11:00:00`, to remove one hour block (for the location 11), I can't add a block for location 12, because the exrule says, that the block is excluded.

**Comment by philharmonie** [comment]
Your idea with "2 RSets" is genius, but it reverses the rrule logic I have implemented, and thinking about it, exploded my head 😂. But after a reboot I got what I tried to achieve:
```

// Remove Blocked
$userBlocked = $blocked[$presence->user->id] ?? [];
foreach ($userBlocked as $block) {
    if ($block->location_id == $presence->location_id) {
        $rset->addExDate($block->start->addHour());
    }
}
```
