### ISSUE TITLE
Nested exrules

### ISSUE THREAD

**Issue by philharmonie** [rlanvin/php-rrule#131]
I have a rset for user's presence:
```php
$rset = new RSet([
   'DTSTART' => "2023-02-20",
   'UNTIL' => "2023-02-26",
   'BYDAY' => "MO,TU,WE,TH,FR"
]);
```
I add an exrule for user's vacations:
```php
$rset->addExRule([
   'DTSTART' => "2023-02-21",
   'UNTIL' => "2023-02-23",
]);
```
The occurences are now:
- 2023-02-20
- 2023-02-24

Now the user removes the vacation from `2023-02-22`. In my database this is a 3rd row "Vacation exception".
Can can I apply this logic to my rset, so that the `2023-02-22` is now excluded from the exrule / added back? I am thinking about adding this as an exrule to the exrule, that would act as an "addRule" like:
```php
$rset->addExRule([
   'DTSTART' => "2023-02-21",
   'UNTIL' => "2023-02-23",
], [
   'DTSTART' => "2023-02-22",
   'UNTIL' => "2023-02-22",
]);
```
How can I realize something like that?

**Comment by rlanvin** [comment]
You would have to treat the user's vacations as a separate RSet.

```php
$rset = new RSet();
$rset->addRRule([
	'DTSTART' => "2023-02-20",
	'UNTIL' => "2023-02-26",
	'BYDAY' => "MO,TU,WE,TH,FR",
	'FREQ' => 'DAILY'
]);

$vacations = new RSet();
$vacations->addRRule([
	'DTSTART' => "2023-02-21",
	'UNTIL' => "2023-02-23",
	'FREQ' => 'DAILY'
]);
$vacations->addExDate('2023-02-22');

$rset->addExRule($vacations);
```

But I think a more common approach for this type of problems is to force the user to delete their 3-day vacations block and to request 2 separate days instead. Usually when the vacation days are not contiguous, it's easier to treat them separately.

**Comment by philharmonie** [comment]
Thank you, this is exactly what I was looking for. I just did not now, that I can add RSets to RSets. And thank you for the hint and I agree. Vacations have been just a common example. In my case the vacation is a "focus hour" that user's have e.g. every day from 9 to 10 am. But there are some exceptions that I want to treat like that.
