### ISSUE TITLE
humanreadable not so much

### ISSUE THREAD

**Issue by kitsguru** [rlanvin/php-rrule#144]
I have a rrule that is the 3rd Wednesday of the month

FREQ=MONTHLY;BYSETPOS=3;BYDAY=WE;INTERVAL=1;DTSTART=20231013

Produces:
monthly on Wednesday, but only the third instance of this set, starting from Oct 13, 2023, forever 

Can this string not  be more readable to non math types? Who understands 'but only the third instance of this set' but us techies. The 'forever' is unnecessary.

**Comment by rlanvin** [comment]
You can disable "forever" with `explicit_infinite` to `false`, as explained [in the documentation](https://github.com/rlanvin/php-rrule/wiki/RRule#humanreadablearray-opt).

For the BYSETPOS, if you have better idea, feel free to submit a pull request.

**Comment by kitsguru** [comment]
"but only the third instance of this set" would be more readable as "but only the third occurrence"
