### ISSUE TITLE
An RRule created with a timestamp start date generates an invalid RFC string

### ISSUE THREAD

**Issue by abrahamguo** [rlanvin/php-rrule#15]
```
<?php
	date_default_timezone_set("America/Chicago");
	require "inc/php-rrule/RRuleInterface.php";
	require "inc/php-rrule/RRule.php";
	require "inc/php-rrule/RSet.php";
	use RRule\RRule;

	$rrule = new RRule(array(
		"freq" => "WEEKLY",
		"dtstart" => 1470323171,
		"interval" => 1
	));

	$rfcString = $rrule->rfcString();
	echo "<b>The RFC string is:</b> " . $rfcString . "<br><br>";
	echo "<b>Parsing RFC string:</b> ";
	$new_rrule = new RRule($rfcString);
```

generates the following output:

**The RFC string is:** DTSTART;TZID=+00:00:20160804T150611 RRULE:FREQ=WEEKLY

**Parsing RFC string:** Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid DTSTART property: date or date time format incorrect' in /path/to/php-rrule/RRule.php:649

This is because the RFC string generated has the timezone set as "+00:00" rather than "UTC".

**Comment by rlanvin** [comment]
Yep that's a bug alright, thanks for the report.

On a related note: when you create the rule with a timestamp, do you expect the results to be in your timezone (America/Chicago in your example)? At the moment they are in UTC since a timestamp is UTC (by definition) but I'm curious to know what you think.

**Comment by abrahamguo** [comment]
Yeah, I think that keeping the results in UTC is probably the correct way to do it. Otherwise, users might get unexpected results (because of a default timezone setting somewhere) that will be hard to track down where they are coming from.

**Comment by rlanvin** [comment]
Thanks. I pushed a fix on dev-master, could you try and let me know if it solves your problem?

**Comment by abrahamguo** [comment]
Yep, seems to be working now!

**Comment by rlanvin** [comment]
Thanks!
