### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Frando** [rlanvin/php-rrule#18]
Hi,
thanks for the library. I'm using it in a [recurring dates module for Drupal 8](https://drupal.org/project/date_recur). I could make use of the getRule method that was recently added but do not want to require a development snapshot, so could you maybe create a 1.3.2 release that includes the recent commits?

**Comment by rlanvin** [comment]
Yes of course. I was planning to make a 1.4 actually (because Semantic Versioning and all that jazz). I'll try to do that asap this week.

**Comment by rlanvin** [comment]
All done, I created a new release 1.4.0.

Let me know if you need other things for your project and of course feel free to create pull requests.
