### ISSUE TITLE
Are rules such as this possible?

### ISSUE THREAD

**Issue by schester44** [rlanvin/php-rrule#19]
Hello, I'm trying to set up rules similar to the following:

`Repeat [Monthly], [BY DAY], Where the Day = [TU] and is the [First] Day Of The Month`
Words in brackets being variables that may change. 

My problem at the moment is i'm unable to return the first Tuesday of every month. It seems `Interval` works to return only 1 day out of the month but `Interval` gets cancelled out if i use it in conjunction with `byday`.

```
$rset = new RSet();
$rset->addRRule(array(
    'freq' => RRule::MONTHLY,
    'interval' => 1,
    'count' => $count,
    'byday' => 'TU',
    'dtstart' => '2015-10-06 09:00:00'
));
```

$count being the total months between dtstart and the end date.

**Comment by rlanvin** [comment]
Sure, try "1TU" for BYDAY.

Also works with "2TU" (the second Tuesday of the month), "-1TU" (the last Friday of the month), and so on.

**Comment by schester44** [comment]
awesome, i appreciate the fast response and apologize for polluting your issues with a question!

**Comment by rlanvin** [comment]
No worries. I'll leave the issue open for now, just to remind me to update the wiki page to make it clearer that this syntax is supported.

**Comment by rlanvin** [comment]
I updated the wiki. Closing this now.
