### ISSUE TITLE
Construct a RSet from RFC string

### ISSUE THREAD

**Issue by rlanvin** [rlanvin/php-rrule#26]
With the Python version (python dateutils), it is possible to parse a RFC string with multiple `RRULE` lines (or `RDATE`, `EXDATE`, `EXRULE`) directly into a RSet. That could be interesting to have as well.

This will require some refactoring of `RRule::parseRfcString()` to make it a factory method, or coding an actual factory method on top of it.

The constructor would still only return a `RRule` since it is probably not possible and not advisable to have the constructor returns a different object.

A RSet should also be able to be formatted into a RFC String with multiple lines.

If this is a feature that would be useful, leave a 👍

**Comment by rlanvin** [comment]
Done.

**Comment by coffeduong** [comment]
Is there any way to refactor RSet back to RFC string?

**Comment by rlanvin** [comment]
At the moment no. The problem is that, according to the RFC, there can be only one DTSTART property for the entire set. However, a RSet object in this library is more flexible and allow combining multiple RRULE, each with a different DTSTART property. This cannot be expressed in a RFC-compliant way. So I don't know how to handle these cases. I'm open to suggestions.

**Comment by coffeduong** [comment]
Ok, I'll try. If there is any new idea, I'll ping you back
