### ISSUE TITLE
DTSTART cannot be part of RRULE

### ISSUE THREAD

**Issue by devvpm** [rlanvin/php-rrule#27]
Get this error while creating rrule object from this string - 

`new RRule("DTSTART=20160107T160000Z;FREQ=DAILY;INTERVAL=1`")

> This string is not compliant with the RFC (DTSTART cannot be part of RRULE). It is accepted as is for compability reasons only.

trace -

> /vendor/rlanvin/php-rrule/src/RRule.php(199): parseRfcString()
rlanvin/php-rrule/src/RRule.php(768): trigger_error()

**Comment by devvpm** [comment]
This fixed the issue.
`preg_replace("/DTSTART=(.*?);/",'DTSTART:${1}'."\nRRULE:",$rrule)`

**Comment by rlanvin** [comment]
This is the intended behavior. As the notice says, your RRULE string is not compliant with the RFC. The lib accepts it only because some other libs (such as the JS lib) generates strings like that... Thank you for the    `preg_replace` code.

**Comment by devvpm** [comment]
However, That preg_replace is not complete. It expects the DTSTART to be at the beginning of the rrule string, which is not the case always. 

So I wrote this function which will return the rrule in the standard format. 

`public function getRecurringRule()
	{
		$rruleParts = explode(';',$this->rrule);
		$startDateIndex = 0;
		foreach($rruleParts as $i=>$rrulePart)
		{
			if(stristr($rrulePart,'DTSTART='))
			{
				$startDateIndex = $i;
				break;
			}
		}
		if($startDateIndex > 0)
		{
			$dateStartElement = $rruleParts[$startDateIndex];
			unset($rruleParts[$startDateIndex]);
			array_unshift($rruleParts , $dateStartElement);
			$rruleFormatted = implode(';',$rruleParts);
		} else {
			$rruleFormatted = $this->rrule;
		}

		return  preg_replace("/DTSTART=(.*?);/",'DTSTART:${1}'."\nRRULE:",$rruleFormatted);
	}`

**Comment by rlanvin** [comment]
You could also do:

```
$rrule = @ new RRule($broken_string); // use @ to mute the notice
$correct_string = $rrule->rfcString(); // will return the RFC-compliant version
```
