### ISSUE TITLE
[Possible Enhancement] Returns the first recurrence after the given datetime instance

### ISSUE THREAD

**Issue by derekchan2k** [rlanvin/php-rrule#28]
Hi there,

Is it possible to include a method in the library that returns the first recurrence after the given datetime instance? Something like what has been done in python-dateutil (https://labix.org/python-dateutil). The method that I am referring to here is rruleset.after(dt, inc=False)

Thank you!

**Comment by rlanvin** [comment]
Hello, you can already do that with [`getOccurencesBetween()`](https://github.com/rlanvin/php-rrule/wiki/RRuleInterface#getoccurrencesbetweenbegin-end). Is there something wrong with it?

**Comment by derekchan2k** [comment]
Hello,

Thanks for the prompt reply.
There is nothing wrong with it. It is just that there is a need to estimate when will the next event occur as a start date and end date parameter is needed. By just allowing me to find out what the next date is without thinking when the next event may possibly occur would be a plus! i.e. If I put the date as today, it could tell me when the next occurrence based on the RRULE rule.

Thanks again.

**Comment by rlanvin** [comment]
> a start date and end date parameter is needed

Well no, actually... As explained in the wiki, `getOccurrencesBetween()` is quite flexible, and you can pass `null` to either `$begin` or `$end` to achieve the result you are looking for.

method call | result
-|-
`getOccurrencesBetween('2017-01-01','2017-01-31')` | between Jan 1st 2017 and Jan 31st 2017 |
`getOccurrencesBetween('2017-01-01',null)` | after Jan 1st 2017 |
`getOccurrencesBetween(null,'2017-01-31')` | before Jan 31st 2017 |
`getOccurrencesBetween(null,null)` | everything (same as `getOccurrences()`) |

Isn't this exactly what you are looking for?

**Comment by derekchan2k** [comment]
Hello again,

Whoops, my bad for not reading the documentation properly. Thanks so much for clarifying. Will close the issue now. 

That is great!
