### ISSUE TITLE
Parse Exdate and Rdate

### ISSUE THREAD

**Issue by mansoorriaaz** [rlanvin/php-rrule#29]
Hai @rlanvin ,
I would like to parse this string
[CASE]
`RRULE:FREQ=MONTHLY;DTSTART=20170201T010000Z;UNTIL=20170228T030000Z;BYDAY=TU,RDATE:20170222T010000Z,EXDATE:20170221T010000Z`.

 The library does parses it but it igores the EXDATE and the RDATE.
[Example output]
`Array
(
    [FREQ] => MONTHLY
    [DTSTART] => 20170201T010000Z
    [UNTIL] => DateTime Object
        (
            [date] => 2017-02-28 03:00:00
            [timezone_type] => 2
            [timezone] => Z
        )
    [BYDAY] => TU,RDATE
)`

I checked the source code but it seems it didn't have the code to parse it.

[Question]
Could we have the ability to parse this kind of rules?  

Thank you so much.

**Comment by rlanvin** [comment]
Hello, this is exactly the feature request #26. I'm closing this issue as it is a duplicate, but feel free to continue the discussion there.
