### ISSUE TITLE
LogicException namespacing bug

### ISSUE THREAD

**Issue by Solinx** [rlanvin/php-rrule#3]
Hi again,

While playing around with RRule I found that on lines 947 and 952 LogicException is referenced within the RRule namespace, rather than the global namespace. 

And perhaps you could reference such dependencies as at the top of the file (e.g. "use LogicException;" ). That provides a bit more clarity concerning the external classes you use.

Thanks in advance! And now I'm off to find out what I did wrong to generate this Exception ;)

Cheers,
Wouter

**Comment by rlanvin** [comment]
Indeed, good catch!

> now I'm off to find out what I did wrong to generate this Exception

You tried to use array access syntax in write mode (e.g. `$rrule[] = x` or `unset($rrule[x])`) which is impossible.

> perhaps you could reference such dependencies as at the top of the file (e.g. "use LogicException;") That provides a bit more clarity concerning the external classes you use.

I do not know what are is "recommended" way of doing it, you might be right. Though at first glance it seems that I would need a fair amount of `use` statements at the beginning of the file (most of the standard Exceptions, `DateTime`, `DateTimeZone`, `DateTimeInterface`, and so on). Care to elaborate the benefits?

**Comment by Solinx** [comment]
> You tried to use array access syntax in write mode (e.g. $rrule[] = x or unset($rrule[x])) which is impossible.

You're right. After a code refactor I ended up using $rrule both for the input var and the RRule object.

> I do not know what are is "recommended" way of doing it, you might be right. Though at first glance it seems that I would need a fair amount of use statements at the beginning of the file (most of the standard Exceptions, DateTime, DateTimeZone, DateTimeInterface, and so on). Care to elaborate the benefits?

As far as I know it's not part of a PSR standard, so I guess there isn't really a clear recommended way of doing it. The benefits are in particular apparent when you've got a file with several 3rd party references and/or long paths. With built-in classes the benefits are certainly less clear. The exception to this though are Exceptions. It is useful for consuming developers to be able to see at a glance which Exceptions could be thrown by a module.

Some of the other benefits are that you're less likely to make typo's like the one I reported here, you get one clear list of dependencies and by grouping all dependencies you'll be made more aware of the moment you're trying to do too much within a single class. At least, that's my personal view on the matter. 

A disadvantage is that the actual line by line code may become somewhat less clear, but if you're using a modern editor (such as PhpStorm) this is not much of an issue.

**Comment by rlanvin** [comment]
Thank you for taking the time to elaborate. I fully agree with you about 3rd party classes and long names. However, for standard PHP classes, I checked what other PHP projects are doing, and it seems that the standard way of doing it is to reference them with their full name. So I'm going to leave it like that for the moment.
