### ISSUE TITLE
Please create a release for the latest developments

### ISSUE THREAD

**Issue by guillaumevoisin** [rlanvin/php-rrule#32]
Hey, there is a difference between the latest tag and the master branch, so I can't benefit from `createFromRfcString` for instance and I don't want to move to master in my composer.json config.
https://github.com/rlanvin/php-rrule/compare/v1.4.2...master

**Comment by rlanvin** [comment]
Hello, I'm still working on it. I'm planning on creating 1.5 soon, but I have a couple of things I need to finish & test first and I've been busy with other projects lately. I'll see if I have time during the week-end. In the meantime you could *temporarily* use `dev-master` on composer instead maybe? I know it's not ideal, but it's a temporary workaround.

**Comment by guillaumevoisin** [comment]
Ok, I'll give a try to the dev-master in the meantime to see if that fixes my issues with the Rset and Until behavior. Thanks for you quick answer ;)

**Comment by rlanvin** [comment]
No problem! Please feel free to share your feedback, it's always good to have testers before a release :)

**Comment by rlanvin** [comment]
Done, version 1.5 has been released.
