### ISSUE TITLE
addExDate is not correct

### ISSUE THREAD

**Issue by coffeduong** [rlanvin/php-rrule#35]
I follow the example here https://github.com/rlanvin/php-rrule/wiki/RSet#iteration But I think it should be like this

```
use RRule\RSet;

$rset = new RSet;
$rset->addRRule([
    'freq' => RRule::DAILY,
    'interval' => 2,
    'count' => 5,
    'dtstart' => '1997-09-02 09:00:00'
]);
$rset->addExDate('1997-09-06 09:00:00');

foreach ( $rset as $occurrence ) {
    echo $occurrence->format('r'),"\n";
}

// output:
// Tue, 02 Sep 1997 09:00:00 +0000
// Thu, 04 Sep 1997 09:00:00 +0000
// (Sat, 06 Sep 1997 09:00:00 +0000 will not be outputed because it is in EXDATE)
// Mon, 08 Sep 1997 09:00:00 +0000
// Wed, 10 Sep 1997 09:00:00 +0000
// Fri, 12 Sep 1997 09:00:00 +0000
```

Because we have count = 5, if 06 Sep 1997 is remove, 12 Sep 1997 should add in the end. In your example you only show 4 occurrences. I think it doesn't make sense :)

**Comment by rlanvin** [comment]
> I think it doesn't make sense :)

Well, I understand your point, but this is how the RFC has been specified, and how a recurrence set works. The COUNT applies to the RRULE only, not the entire set.

To make things clearer, here are some examples:

- If you create a set with 2 rules, one with COUNT 5 and the other with COUNT 10, the total occurrences will be anywhere between 5 (if they are all the same) and 10 (if they are all different).
- If you create a set with 1 rule with COUNT 5, and then add 1 RDATE (not part of the rrule) then the total number of occurrences will be 6.
- And so on.

If you want the behavior you are describing, I suggest you remove the COUNT altogether and instead select only the first 5 occurrences (use `getOccurrences(5)` for example).

I hope this makes sense to you now.

**Comment by coffeduong** [comment]
This make sense now :) Thank you very much!
