### ISSUE TITLE
Unexpected behavior using WEEKLY with INTERVAL greater than 1 and BYDAY 

### ISSUE THREAD

**Issue by jasonhuskey** [rlanvin/php-rrule#39]
I'm trying to create a bi-weekly rule that occurs every other Friday.  I would expect the first occurrence to always be the first Friday after the DTSTART but that is only true when the WKST is one day after the BYDAY.
Example:

```
'FREQ' => 'WEEKLY',
'INTERVAL' => 2,
'BYDAY' => 'FR',
'WKST' => 'SU',
'DTSTART' => '2017-10-07',
'COUNT' => 10,
```
With a DTSTART of 2017-10-07 I would expect the first occurrence to be 2017-10-13 but instead it is 2017-10-20.

If the DTSTART is changed to 2017-10-08 then the first occurrence changes to 2017-10-13.

It works as I expect if the WKST is always one day after the BYDAY as in the following example:

```
'FREQ' => 'WEEKLY',
'INTERVAL' => 2,
'BYDAY' => 'FR',
'WKST' => 'SA',
'DTSTART' => '2017-10-07',
'COUNT' => 10,
```

Is this the intended behavior?

**Comment by rlanvin** [comment]
> Is this the intended behavior?

After a quick glance, I'd say yes.

Let's look at the first rule:

- 2017-10-07 is a Saturday. 
- Week starts on Sunday, therefore the starting week is computed to be 2017-10-02 to 2017-10-08
- The first Friday of the first week is therefore computed to 2017-10-06. This is before DTSTART, so ignored.
- Interval is 2, so 2 weeks later is Friday 2017-10-20

If the DTSTART is 2017-10-08 (a Sunday, matching WKST), then the starting week is 2017-10-08 to 2017-10-15 and therefore the first Friday is 2017-10-13.

Same if you change WKST to Saturday, then it matches your DTSTART of 2017-10-17.

**Comment by jasonhuskey** [comment]
Ok, I get it now.  The 7 day period that includes the DTSTART will have the first occurrence of the RRule.  If the DTSTART is after the first occurrence then it will go to the next occurrence.

Thanks for the answer and thanks for writing this package.

**Comment by rlanvin** [comment]
Glad I could help!
