### ISSUE TITLE
Generate Recurrence Like Iphone Calendar

### ISSUE THREAD

**Issue by samktest** [rlanvin/php-rrule#41]
how to design rrule for iphone recurring event process
1.Freq=monthly and i want to repeat that event on fifth or last weekday or fifth or last weekend days 
so how i can do that with rrule can you provide some guidelines to create recurring events as like iphone calendar works
![image](https://user-images.githubusercontent.com/34028679/33266130-4e038f90-d39a-11e7-8818-7b2f20a3bfb6.png)

**Comment by rlanvin** [comment]
Why don't you look at how the iPhone is storing those events? I'm sure you can export them in iCal format and look at the `RRULE` part, and just copy it.

>  can you provide some guidelines to create recurring events as like iphone calendar works

I'll give you some pointers, but please understand this library is only a parser for RRULE/iCalendar format. So if you are now sure how to use this syntax, the easier is simply to copy the rules generated by the iPhone. For more detailed info please refer to the [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.3.10), as well as [the wiki](https://github.com/rlanvin/php-rrule/wiki/RRule).

### Nth day, when day is named explicitly

Use `BYDAY` with an integer. Examples: `BYDAY=1MO`  is the first Monday, `2MO` is the second Monday, `-1MO` is the last Monday, and so on. Multiple days can be combined.

###  Nth day, when "day" is not named explicitely

Use `BYMONTHDAY` or `BYYEARDAY`. `BYMONTHDAY=3` is the 3rd day of the month, `-1` is the last day of the month, `BYYEARDAY=1` is the first day of the year, and so on. Multiple days can be combined.

###  Nth weekday/weekend day

Use a combination of `BYDAY` and `BYSETPOS`. For example "the last weekday of the month" could be represented as:

       FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1

Hope this helps.
