### ISSUE TITLE
Daylight savings

### ISSUE THREAD

**Issue by morinluc0** [rlanvin/php-rrule#47]
I think I am running into an issue with a daylight savings and timezones. 

When I create a php-rrule that the repeating time starts before a daylight savings and crosses over a daylight savings time change the UTC time that is being generated is not changing based on timezone that was entered. 

For example 

`[value] => 2018-03-19T13:30:00`
`[end_value] => 2018-03-19T21:00:00`
`[rrule] => RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;UNTIL=20180331T000000Z`
`[infinite] => 0`
`[timezone] => America/Toronto`

America/Toronto should be have a DST of +4 before 11-Mar-2018

My repeating events having times of the following which are correct. 

`2018-03-19T13:30:00        | 2018-03-19T21:00:00`
`2018-03-20T13:30:00        | 2018-03-20T21:00:00`
`2018-03-21T13:30:00        | 2018-03-21T21:00:00`
`2018-03-22T13:30:00        | 2018-03-22T21:00:00`
`2018-03-23T13:30:00        | 2018-03-23T21:00:00`
`2018-03-24T13:30:00        | 2018-03-24T21:00:00`
`2018-03-25T13:30:00        | 2018-03-25T21:00:00`
`2018-03-26T13:30:00        | 2018-03-26T21:00:00`
`2018-03-27T13:30:00        | 2018-03-27T21:00:00`
`2018-03-28T13:30:00        | 2018-03-28T21:00:00`
`2018-03-29T13:30:00        | 2018-03-29T21:00:00`
`2018-03-30T13:30:00        | 2018-03-30T21:00:00`

Then If I set the Rrule to before the 11-Mar-2018 it set's all of the occurrences to the initial time set +5.

`[value] => 2018-03-10T14:30:00`
`[end_value] => 2018-03-10T22:00:00`
`[rrule] => RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;UNTIL=20180331T000000Z`
`[infinite] => 0`
`[timezone] => America/Toronto`

`2018-03-10T14:30:00        | 2018-03-10T22:00:00`
`2018-03-11T14:30:00        | 2018-03-11T22:00:00`
`2018-03-12T14:30:00        | 2018-03-12T22:00:00`
`2018-03-13T14:30:00        | 2018-03-13T22:00:00`
`2018-03-14T14:30:00        | 2018-03-14T22:00:00`
`2018-03-15T14:30:00        | 2018-03-15T22:00:00`
`2018-03-16T14:30:00        | 2018-03-16T22:00:00`
`2018-03-17T14:30:00        | 2018-03-17T22:00:00`
`2018-03-18T14:30:00        | 2018-03-18T22:00:00`
`2018-03-19T14:30:00        | 2018-03-19T22:00:00`
`2018-03-20T14:30:00        | 2018-03-20T22:00:00`
`2018-03-21T14:30:00        | 2018-03-21T22:00:00`
`2018-03-22T14:30:00        | 2018-03-22T22:00:00`
`2018-03-23T14:30:00        | 2018-03-23T22:00:00`
`2018-03-24T14:30:00        | 2018-03-24T22:00:00`
`2018-03-25T14:30:00        | 2018-03-25T22:00:00`
`2018-03-26T14:30:00        | 2018-03-26T22:00:00`
`2018-03-27T14:30:00        | 2018-03-27T22:00:00`
`2018-03-28T14:30:00        | 2018-03-28T22:00:00`
`2018-03-29T14:30:00        | 2018-03-29T22:00:00`
`2018-03-30T14:30:00        | 2018-03-30T22:00:00`

 Shouldn't the occurrences switch to +4 hours after the 11-Mar-2018 ?

**Comment by rlanvin** [comment]
This is a good question, and admittedly the behavior can be a bit confusing.

If you ask the lib to produce occurrences at a certain time in a certain timezone (say, 14:30 in America/Toronto), all the results will be at 14:30 in America/Toronto. The actual offset with UTC doesn't matter. Say for example you have meeting every Monday at 8am. It'll still be at 8am during DST, won't it?

You can achieve the behavior you are a describing if you set the DTSTART in UTC and convert the occurrences on the fly. Because then the lib will work with absolute UTC times, but the meaning of the time in your local timezone (America/Toronto) will change based on the date. Example:


    $rrule = new RRule(
    	'RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;UNTIL=20180331T000000Z',
    	date_create('2018-03-10 13:30:00', new DateTimeZone('America/Toronto'))->setTimeZone(new DateTimeZone('UTC')) // force the start in UTC
    );

    foreach ( $rrule as $occurrence ) {
    	echo $occurrence->setTimeZone(new DateTimeZone('America/Toronto'))->format('l jS F Y H:i:s e P'),"\n";
    }

This will produce:

> Saturday 10th March 2018 13:30:00 America/Toronto -05:00
> Sunday 11th March 2018 14:30:00 America/Toronto -04:00
> Monday 12th March 2018 14:30:00 America/Toronto -04:00
> Tuesday 13th March 2018 14:30:00 America/Toronto -04:00

Does this answer your problem?

**Comment by morinluc0** [comment]
Yes it does answer my question, I will modify the my behavior to send in a UTC time. 

Thank you for clearing up that confusion.
