### ISSUE TITLE
Support question: Find first occurrence in the future

### ISSUE THREAD

**Issue by spoetnik** [rlanvin/php-rrule#51]
I hope you don't mind me asking a support question, if so, please close this issue.

I am looking for the first 'occurrence' for an event in the future, with a 'DTSTART' in history.
A possible solution would be to create, say 10, occurrences from 'DTSTART', check if there is one in the future, if not create an other 10 etc...
Not very neatly I think. Is there a better solution for this kind of rule?

**Comment by rlanvin** [comment]
No worries I don't mind, however I'm not quite sure what your question is exactly. You don't need to create N occurrences and then check them. You can directly use a `foreach` loop and if the occurrence is greater than "today" (I guess that is what you mean by "future") then `break` out of the loop. Does this answer your question? If not, please provide more details so I can understand your case a bit better.

**Comment by spoetnik** [comment]
Thanks!
The idea is this:
A visitor on my website can subscribe to an event. An event has a 'start_date', and a RRule for the recurring events. This date is probably in the past.
When a visitor visits the page for the event, I want to present them with the first occurrence for this event in the near future.

I thought that looping over each past occurrence, check if the date is in the future, could be a costly operation. Say it is a daily event, and I have to loop over more than a year of occurrences.

I hoped RRule would have some function for it. If not the loop is the way to go!

**Comment by rlanvin** [comment]
> I hoped RRule would have some function for it. If not the loop is the way to go!

Well sure you could use `getOccurrencesBetween($begin, null, 1)` where `$begin` would be "today" but it does exactly that (a loop, a if and a break).

There is no way for the lib to auto-magically calculate an occurrence without calculating all occurrences before. I recommend you read the discussion on issue #40 about performance where this topic is touched upon.

Now in your situation, *if* performance is a problem, you can simply use some for of caching. But that would be outside the scope of this lib.

Hope I answered your question!

**Comment by spoetnik** [comment]
Thanks a lot for the help!
the `getOccurrencesBetween($begin, null, 1)` trick worked for for me!
