### ISSUE TITLE
Getting first upcoming and one past occurrence?

### ISSUE THREAD

**Issue by buzzclue** [rlanvin/php-rrule#60]
Is there a way to get only one upcoming and past occurrence? instead of all occurrences?

**Comment by rlanvin** [comment]
Well getOccurrences and getOcurrences between get a $limit parameter, is that what you want?

**Comment by buzzclue** [comment]
I just want to get the first upcoming and last past date... getOccurrences gives all dates and i want to avoid loop to find first upcoming date.

**Comment by rlanvin** [comment]
What about `getOccurrencesBetween`? `getOccurrencesBetween($today, null, 1)` will return 1 occurrence after today, so the first upcoming occurrence. For the past it's a bit more tricky, but maybe `array_pop(getOcurrencesBetween(null,$today))`? I could add some helpers, but I think this workaround should work.

**Comment by buzzclue** [comment]
I have another scenario, i will be grateful if you may give me workaround? i want to get nth occurrence one way is i change the limit and array_pop like you did previously but lets say nth number is 500 or even higher in this case performance is the question especially memory?

**Comment by rlanvin** [comment]
You would have to test the performance. To get the 500th occurrence after a date there is no other way but to calculate all occurrences to that date, and then 500 occurrences after that date (this is due to how RRULE work), which is was getOccurrencesBetween will do. That being said 500 is really a lot - even for a daily event that's almost 2 years. What is your need exactly?

**Comment by buzzclue** [comment]
I have an event page where i display the current event details and navigation for next and previous occurrence. I know the chances are less or maybe none that user will get to 500th occurrence. 

Follow this:

Lets say today is 20th occurrence now to get one previous date i will do **$rrule->getOccurrencesBetween( null, $current );** and will get all past dates. I thought it would be easier if we can simply get nth occurrence instead? 

Oh One thing previous occurrence is on second last index when we do **$rrule->getOccurrencesBetween( null, $current );** 

Please let me know if you need more clarification? BTW loved your work.

**Comment by rlanvin** [comment]
Yes I agree, the interface could be made easier for this use case, with some helper functions. I'll have a look when I have a moment.

> Oh One thing previous occurrence is on second last index when we do $rrule->getOccurrencesBetween( null, $current );
Only if $current itself matches the rule I think?

**Comment by buzzclue** [comment]
> Only if $current itself matches the rule I think?

Yes that is correct.

**Comment by rlanvin** [comment]
Hello, I added the helpers into master. Please check version 2.0.0-rc1 and give me your feedback!

**Comment by buzzclue** [comment]
You are awesome!
