### ISSUE TITLE
RRULE without end date throws error

### ISSUE THREAD

**Issue by drnikki** [rlanvin/php-rrule#64]
Hi!

Thanks for the great library.   When I pass in a simple RRULE (the three steps are a quirk of the larger project...):
```php
$datestring =  'RRULE:FREQ=WEEKLY;BYDAY=WE';
$datearray = \RRule\RfcParser::parseRRule($datestring); 
$rrule = new RRule($datearray);
```
and then try to find the next occurrence (based on code you've provided elsewhere here) 
```php
$today = date('Y-m-d\TH:i:m');
$next = $rrule->getOccurrencesBetween($today, null, 1);
```
I get the following error: 
```
Error: Call to a member function format() on boolean in RRule\RRule->iterate() (line 1659 of /var/www/vendor/rlanvin/php-rrule/src/RRule.php).
RRule\RRule->iterate() (Line: 1035)
RRule\RRule->next() (Line: 194)
```

However, when I add an end date, the error no longer appears (
`RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=22000101T070000Z`).

We've worked around this locally by appending a far future UNTIL for user-created repeating events.

**Comment by rlanvin** [comment]
Thanks for the bug report. This is very strange, I cannot reproduce it with the code you provided. RRULE without ends are fully tested and that's the first time I hear of this. Could you tell me the version of the lib your are using, and also your version of PHP?

**Comment by McGo** [comment]
I can also not reproduce the error with the code given above and latest officially released version (1.6.3)

**Comment by drnikki** [comment]
Thanks, both. I was doing this in the context of a Drupal module, so it is likely something to do with that environment.  Adding an enddate to the RRule before creation does fix it in the Drupal context, so this seems like a good-enough solution for anyone who might be experiencing this error in the future.

**Comment by rlanvin** [comment]
It's a workaround but definitely not a satisfying solution. At this point there is nothing I can do without being able to reproduce this issue unfortunately. Feel free to provide more details, or alternatively I think it would be good to raise this issue with the author of the Drupal module you are talking about.
