### ISSUE TITLE
InvalidArgumentException: The locale option does not look like a valid locale

### ISSUE THREAD

**Issue by madeincosmos** [rlanvin/php-rrule#67]
This error is only triggered when `intl` fails to load: 

```
InvalidArgumentException: The locale option does not look like a valid locale: LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C. For more option install the intl extension. 
```

The regex here expects locale in format such as `en_US.UTF-8` instead of what's given:

https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L2084

According to `setlocale` specs, all these extra parameters will normally be returned for `setLocale(LC_ALL, 0)`, which is called here:

https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L2193

To only get `en_US.UTF-8` we'll want to use `LC_CTYPE` instead:

https://www.php.net/manual/en/function.setlocale.php#106811

Applying this change on my test site solved the problem for me.

**Comment by rlanvin** [comment]
Good catch. Do you want to create a pull request?

**Comment by madeincosmos** [comment]
Sure, there it is 🙂

**Comment by bor0** [comment]
@madeincosmos thanks for working on this!

@rlanvin our project depends on this fix, is there a new release planned anytime soon?

**Comment by rlanvin** [comment]
@bor0 Sure, I just released version 2.1.0 now.

**Comment by bor0** [comment]
@rlanvin thank you! Kudos for the fast response :)

**Comment by Froxz** [comment]
Hi @madeincosmos  @rlanvin 

Have same issue with:

`The locale option does not look like a valid locale: C.UTF-8. For more option install the intl extension.`

In order to fix this is mandatory to install `intl`?

**Comment by rlanvin** [comment]
> In order to fix this is mandatory to install intl?

Hi @Froxz, no it's not - I believe the reason you're seeing this error is that "C" as a locale is simply not supported (since it doesn't correspond to any language file).

**Comment by Froxz** [comment]
Hi @rlanvin thank you for reply.

Seems this works without chaning php/server locale:

```php
$rrule->humanReadable([
	'use_intl' => false,
	'locale' => 'en',
]);
```

P.S. Thank you for amazing library.
