### ISSUE TITLE
[Request] Rset function toString()

### ISSUE THREAD

**Issue by badochov** [rlanvin/php-rrule#76]
I made a function for generating string from Rset i'd be glad to see equivalent in official distribution

`    public function toString()
    {
        $rrules = $this->getRRules();
        $string = '';

        foreach ($rrules as $rrule)
            $string .= $rrule->rfcString() . PHP_EOL;

        $exdates = $this->getExDates();
        if (count($exdates)) {
            $string .= 'EXDATE:';
            foreach ($exdates as $date)
                $string .= $date->format(ISO_FORMAT) . ',';

            $string = rtrim($string, ',');

            $string .= PHP_EOL;
        }

        return $string;`

that's my code

**Comment by rlanvin** [comment]
Hello, thanks for your contribution. There is already a ticket (#37) about this feature, where we discuss the challenge with this method. Feel free to participate in the conversation there.
