### ISSUE TITLE
Change getOccurencesBetween() to getOccurrencesBetween()

### ISSUE THREAD

**Issue by sINusBob** [rlanvin/php-rrule#77]
In the documentation -- https://github.com/rlanvin/php-rrule/wiki/RRuleInterface -- informs getOccurencesBetween(), but corret is getOccurrencesBetween()

![image](https://user-images.githubusercontent.com/7133469/66055891-a90bc580-e50c-11e9-9c3a-8526bb2f9d83.png)

**Comment by rlanvin** [comment]
Good catch, it's fixed.
