### ISSUE TITLE
RRule size limited to 1460

### ISSUE THREAD

**Issue by carrphilip** [rlanvin/php-rrule#78]
An issue with v2.1.0 that did not exist in v1.6.2

A weekly recurrance rule is limited to 1460 elements whereas the earlier version seems unlimited.  Code example below:

$rruleConfig = [
	'FREQ' => "WEEKLY",
	'INTERVAL' => 1,
	'DTSTART' => 1572503950,
	'COUNT' => 2000
];

$rrule = new RRule\RRule($rruleConfig);
$instCount=0;

foreach ($rrule as $instCount => $row){
	$instDT =  date_timestamp_get($row);
	echo $instCount." ".$instDT."<br/>";
	$instCount ++;
}

**Comment by rlanvin** [comment]
Hey thanks, that's a very good catch! I just released v2.2.0 including the fix.
