### ISSUE TITLE
PHP / Mysql Case Example Please ?

### ISSUE THREAD

**Issue by compumatter** [rlanvin/php-rrule#79]
Hello,

I have just created a plugin for capturing / storing calendar data according to the iCalendar 5545 rrule specifications ([see example](http://compumatter.com/test/datetime/wp-plugin-ui.jpg))

I came across your significant contribution but would find it of great value to myself and probably to others if we were to know how you would apply to a query against the database and parsing the return.

For instance, a query like this is asking for all events between 2 provided timestamps as well as those events with no end date provided ie; 'Never' ending for which I use a 12/31/9999 date by default.

The query looks like this: 
```
SELECT cm_66_cm_children.c_field1 as event_title, cm_66_cm_children.c_field11 first_possible_date, cm_66_cm_children.c_field12 last_possible_date,cm_66_cm_children.c_field10 rrule 
FROM cm_66_cm_children 
WHERE cm_66_cm_children.c_field11 >= 1582685860 and (cm_66_cm_children.c_field12 < 1583895460 || cm_66_cm_children.c_field12 = 253402243200) order by cm_66_cm_children.c_field11
```
The SQL Query results in my case look like this 
<table border='1' style='border-color:red;width:100%;font-size:10px'>
<tr><th> Event Title</th><th>First Possible Date</th><th>Last Possible Date</th><th>RRule</th></tr>
<tr><td>Other Event 7</td><td>1582770000 </td><td>1582827600 </td><td>FREQ=DAILY;INTERVAL=1;UNTIL=20200227T182000Z</td></tr>
<tr><td>Other Event 6</td><td>1582855200 </td><td>1582912800 </td><td> FREQ=DAILY;INTERVAL=1;UNTIL=20200227T182000Z</td></tr>
<tr><td>Other Event 5</td><td>1582917480 </td><td>1582975080 </td><td>FREQ=DAILY;INTERVAL=1;UNTIL=20200229T111800Z</td></tr>
<tr><td>Other Event 1</td><td>1582931460 </td><td>1582989060 </td><td>FREQ=DAILY;INTERVAL=1;UNTIL=20200229T151100Z</td></tr>
<tr><td>Other Event 3 </td><td>1583003880 </td><td>1583061480</td><td>FREQ=DAILY;INTERVAL=1;UNTIL=20200301T111800Z</td></tr>
<tr><td>Ladies Night</td><td>1583006700 </td><td>253402243200</td><td>FREQ=WEEKLY;INTERVAL=1;BYDAY=SA</td></tr>
<tr><td>Family and Kids Pizza Night</td><td>1583380800</td><td>253402243200</td><td>FREQ=WEEKLY;INTERVAL=3;BYDAY=MO,WE,SA</td></tr>
<tr><td>Other Event 2</td><td>1583883540</td><td>253402243200</td><td>FREQ=WEEKLY;INTERVAL=1;BYDAY=TU</td></tr>
</table>
PHP arrays containing the above returns might translate to this:

``` 
$event_titles[]=$results['event_title'];
$event_first_dates[]=$results['first_possible_date'];
$event_last_dates[]=$results['last_possible_date'];
$event_rrules[]=$results['rrule'];
```

**My Question For You:**

How would we apply your wonderful code to these resulting arrays to gives a list of the 'VALID' events from the results set. 

Or perhaps you would be approaching this using an entirely different methodology...

Would love to hear your thoughts on this and will contribute some $$ towards your time for assisting.

Thanks.

Jay 
CompuMatter

**Comment by rlanvin** [comment]
> How would we apply your wonderful code to these resulting arrays to gives a list of the 'VALID' events from the results set.

I would loop through the results, creating an new RRule object for each row, and use the method `occursAt()` to determine whether the event is valid or not.

**Comment by compumatter** [comment]
Thanks for the reply rlanvan 

I am unclear on the very beginnings of your software's implementation.

I see that function occursAt requires a $date format. 

Yet I am not seeing how occursAt knows what rrules it is comparing that $date against ?

I'm hoping for a linear example / popcorn trail that might show how we would accomplish the end goal.

So using my earlier example of having 4 arrays of data:

```
# Last desired timestamp to display ie; 2 weeks from today 
$end_timestamp=1583968158
# each line is the events title 
$event_titles[]=$results['event_title'];
# each value is a timestamp of the first possible date 
$event_first_dates[]=$results['first_possible_date'];
# each value is a timestamp of the last possible date (includes Never ending dates of 12/31/9999) 
$event_last_dates[]=$results['last_possible_date'];
# each value contains an rrule for example: FREQ=DAILY;INTERVAL=1;UNTIL=20200301T111800Z
$event_rrules[]=$results['rrule'];
```

I would then include your software: 

```
include("php-rrule-master/src/RRuleInterface.php");
include("php-rrule-master/src/RRuleTrait.php");
include("php-rrule-master/src/RSet.php");

// perhaps loop through the arrays 
for($r=0;$r<count($event_rules);$r++){


}
```
Beyond the above, I am not understanding / connecting the dots which would 
- limit the events displayed to only those which fall between 2 weeks based on their rrule 

Your thoughts?

Thanks again.

Jay

**Comment by pluk77** [comment]
Jay, I have not tried this code, so there might be some small mistakes in it, but it should help you finding a solution I think. (happy to update my response if you find errors)

First make sure your events are in a usable format. A simple array could work:

    $events[1] = array(
      'event_title'=> 'Other Event 7',
      'first_possible_date' => 1582770000
      'last_possible_date' => 1582827600
      'rrule' => 'FREQ=DAILY;INTERVAL=1;UNTIL=20200227T182000Z'
    );

Now process them as a set, or individually:

    // create a new set of rules, which can be processed as one
    $rset = new RSet();
    $start_date = new DateTime(); // set to the first date of your period
    $end_date = new DateTime(); // set to the last date of your period
    foreach($events as $key => $event)
    {
      // create a new rrule object based on the string form the database and
      // the start date. this is required as the rule could have started a few months ago and
      // we do not want to include past dates
      $rule = new RRule($event['rrule'],$start_date);

      // add the individual rule to the set
      $rset->addRRule($rule);
    }

    // optional: if you have public holidays you want to exclude, remove them from the set
    // by ways of an exception date
    foreach($this->getPublicHolidays() as $exDate) 
    {
      $rset->addExDate($exDate);
    }

    // Return all the occurrences after a date, before a date, or between two dates.
    // returns an array of \DateTime objects, which are all the VALID event dates.
    $occurrences = $rset->getOccurrencesBetween($start_date, $end_date);

If you want to process the individual events, you could do it like this:

    $start_date = new DateTime(); // set to the first date of your period
    $end_date = new DateTime(); // set to the last date of your period
    foreach($events as $key => $event)
    {
      // create a new rrule object based on the string form the database and
      // the start date. this is required as the rule could have started a few months ago and
      // we do not want to include past dates
      $rule = new RRule($event['rrule'],$start_date);

      // this will populate all VALID occurrences of this specific event. 
      $events['occurrences'] = $rule->getOccurrencesBetween($start_date, $end_date);
    }

**Comment by rlanvin** [comment]
@compumatter I assumed by "valid events" you meant "the events that occurs at a given date", which is what `occursAt()` is for.

But now I'm thinking you might have a different definition of what a "valid" event is.

If a "valid" event for you is "any event that occurs at least once between 2 dates", then as @pluk77 said you can use `getOccurrencesBetween()` and check if an event has at least one occurrence in the given timeframe.

**Comment by compumatter** [comment]
Hello and thank you Marcel and Remi for your replies.

I have not tested these yet but will be doing so within the hour.  I am grateful for the responses and am glad I have found this library.

Jay

**Comment by compumatter** [comment]
Starting 'as a set' using the intro code above I have included the Rset.php and other required php files.  However when starting with 

$rset = new RSet();  

Am finding this in the log files:  PHP Fatal error:  Uncaught Error: Class 'RSet' not found 

Any idea why this would be?

**Comment by compumatter** [comment]
<h3>Range Of Dates Possible</h3>
I am requesting a list of matching events that fall between a
<ul>
<li><b>start_date</b> of 1582404540 ( 2020 Feb 22 Saturday 12:49  )  AND an</li>
<li><b>end_date</b> of  1584071059 ( 2020 Mar 12 Thursday 20:44  )  </li>
</ul>
<h3>RRule Used</h3>
<ul>
<li>FREQ=DAILY;INTERVAL=1;UNTIL=20200305T044900Z</li>
</ul>
<h3>This Event Date Range</h3>
In the example provided below, I have provided the following values<br><br>
This Particular Events <b>First Possible Date</b>:1583354940 ( 2020 Mar 4 Wednesday 12:49  ) <br>
This Particular Events <b>Last Possible Date</b>:1583700540 ( 2020 Mar 8 Sunday 13:49  ) (same date/time) <br>

<h3>Dates Returned From getOccurrencesBetween</h3>
<table border="1" width="300" align="left" style="position:relative;"><tbody><tr><th>Time Of Event</th><th>Timezone</th></tr><tr><td>2020-02-22 20:49</td><td>UTC</td></tr><tr><td>2020-02-23 20:49</td><td>UTC</td></tr><tr><td>2020-02-24 20:49</td><td>UTC</td></tr><tr><td>2020-02-25 20:49</td><td>UTC</td></tr><tr><td>2020-02-26 20:49</td><td>UTC</td></tr><tr><td>2020-02-27 20:49</td><td>UTC</td></tr><tr><td>2020-02-28 20:49</td><td>UTC</td></tr><tr><td>2020-02-29 20:49</td><td>UTC</td></tr><tr><td>2020-03-01 20:49</td><td>UTC</td></tr><tr><td>2020-03-02 20:49</td><td>UTC</td></tr><tr><td>2020-03-03 20:49</td><td>UTC</td></tr><tr><td>2020-03-04 20:49</td><td>UTC</td></tr></tbody></table><div style="float:left;clear:both;display:block;width:100%;position:relative;margin-top:1em;">
What I expected to be returned:<br>
Although the start_date requested was Feb 27th, the first_possible_date of this event was in fact Mar 4th so my expectation was it would not be a VALID date and so not be returned as an Event.<br><br>
So I believed nothing before Mar 4th would be returned.<br><br>
Is my understanding of what the $start_date / $end_date mean inaccurate and if so, can you help me with that.
</div>

**Comment by compumatter** [comment]
<h3>Range Of Dates Possible</h3>
I am requesting a list of matching events that fall between a
<ul>
<li><b>start_date</b> of 1582404540 ( 2020 Feb 22 Saturday 12:49  )  AND an</li>
<li><b>end_date</b> of  1584071059 ( 2020 Mar 12 Thursday 20:44  )  </li>
</ul>
<h3>RRule Used</h3>
<ul>
<li>FREQ=DAILY;INTERVAL=1;UNTIL=20200305T044900Z</li>
</ul>
<h3>This Event Date Range</h3>
In the example provided below, I have provided the following values<br><br>
This Particular Events <b>First Possible Date</b>:1583354940 ( 2020 Mar 4 Wednesday 12:49  ) <br>
This Particular Events <b>Last Possible Date</b>:1583700540 ( 2020 Mar 8 Sunday 13:49  ) (same date/time) <br>

<h3>Dates Returned From getOccurrencesBetween</h3>
<table border="1" width="300" align="left" style="position:relative;"><tbody><tr><th>Time Of Event</th><th>Timezone</th></tr><tr><td>2020-02-22 20:49</td><td>UTC</td></tr><tr><td>2020-02-23 20:49</td><td>UTC</td></tr><tr><td>2020-02-24 20:49</td><td>UTC</td></tr><tr><td>2020-02-25 20:49</td><td>UTC</td></tr><tr><td>2020-02-26 20:49</td><td>UTC</td></tr><tr><td>2020-02-27 20:49</td><td>UTC</td></tr><tr><td>2020-02-28 20:49</td><td>UTC</td></tr><tr><td>2020-02-29 20:49</td><td>UTC</td></tr><tr><td>2020-03-01 20:49</td><td>UTC</td></tr><tr><td>2020-03-02 20:49</td><td>UTC</td></tr><tr><td>2020-03-03 20:49</td><td>UTC</td></tr><tr><td>2020-03-04 20:49</td><td>UTC</td></tr></tbody></table><div style="float:left;clear:both;display:block;width:100%;position:relative;margin-top:1em;">
What I expected to be returned:<br>
Although the start_date requested was Feb 27th, the first_possible_date of this event was in fact Mar 4th so my expectation was it would not be a VALID date and so not be returned as an Event.<br><br>
So I believed nothing before Mar 4th would be returned.<br><br>
Is my understanding of what the $start_date / $end_date mean inaccurate and if so, can you help me with that.
</div>

<h3>Code Used Below</h3>

```
<?php
define('PLUGINS_DIR','/home/ws-000000015-ci/public_html/wp-content/plugins');
include(PLUGINS_DIR."/cm-calendar/both-ends/php-rrule-master/src/RRuleInterface.php");
include(PLUGINS_DIR."/cm-calendar/both-ends/php-rrule-master/src/RRuleTrait.php");
include(PLUGINS_DIR."/cm-calendar/both-ends/php-rrule-master/src/RSet.php");
include(PLUGINS_DIR."/cm-calendar/both-ends/php-rrule-master/src/RRule.php");
include(PLUGINS_DIR."/cm-calendar/both-ends/php-rrule-master/src/RfcParser.php");

# Example database return for a single record
$results_many[0]['c_field1']='Pizza Neight';
$results_many[0]['c_field11']='1583354940';  // GMT: Thursday, March 4, 2020 20:49:00 AM
$results_many[0]['c_field12']='1583700540';  // GMT: Thursday, March 8, 2020 20:49:00 AM  (1 day later)
$results_many[0]['c_field10']='FREQ=DAILY;INTERVAL=1;UNTIL=20200305T044900Z';

# Combined these 2 values indicate the 'Range' of events that would be visible if their rrule allows for it
$start_date=1582404540; # Friday, February 22, 2020 4:44:19 AM
$end_date  =1584071059; # Friday, March 13, 2020 3:44:19 AM   (2 weeks after start_date)

# Now we parse the database results into an $events array
#  Undefined index: c_field11 in /home/ws-000000015-ci/public_html/test/rset/index.php on line 22
for($rc=0;$rc<count($results_many);$rc++){
  $events[$rc]['event_title']=$results_many[$rc]['c_field1'];
  $events[$rc]['event_first_possible_date']=$results_many[$rc]['c_field11'];
  $events[$rc]['event_last_possible_date']=$results_many[$rc]['c_field12'];
  $events[$rc]['event_rrule']=$results_many[$rc]['c_field10'];
}

use RRule\RRule;
use RRule\RSet;
$rset = new RSet();

# Now we extract the rrules from the $events
for($e=0;$e<count($events);$e++){
  if(isset($events[$e]['event_rrule'])){
    // create a new rrule object based on the string form the database and
    /* the start date. this is required as the rule could have started a few
       months ago and we do not want to include past dates */
    $rule = new RRule($events[$e]['event_rrule'],$start_date);
    // add the individual rule to the set
    $rset->addRRule($rule);
  }
}

// Return all the occurrences after a date, before a date, or between two dates.
// returns an array of \DateTime objects, which are all the VALID event dates.
$occurrences = $rset->getOccurrencesBetween($start_date, $end_date);


# Dates Returned From getOccurrencesBetween
echo "<table border='1' width='300' align='left' style='position:relative;'>";
echo "<tr><th>Time Of Event</th><th>Timezone</th></tr>";
for($o=0;$o<count($occurrences);$o++){
   # var_export($occurrences[$o])."<hr>";
    #error_log("Func: TIMESTAMP IN $timezone before seconds removed : ".$dateTime->getTimestamp());
    echo "<tr>";
# DateTime::__set_state(array( 'date' => '2020-03-04 03:58:46.000000', 'timezone_type' => 3, 'timezone' => 'UTC', ))DateTime::__set_state(array( 'date' => '2020-03-05 03:58:46.000000', 'timezone_type' => 3, 'timezone' => 'UTC', ))
    $date=$occurrences[$o]->format('Y-m-d H:i');
    echo "<td>".$date."</td><td>".((array)$occurrences[$o])['timezone']."</td>";

    echo "</tr>";
}
echo "</table>";
?>

```

**Comment by compumatter** [comment]
Remi and Marcel - I have sent you some funds as a thank you for your software and your answers

I have noticed Remi you have not claimed these funds sent from paypal.  Please advise if your email is different than @cloudconnected.fr

**Comment by rlanvin** [comment]
> Although the start_date requested was Feb 27th, the first_possible_date of this event was in fact Mar 4th

The `first_possible_date` is a field in your table, but you don't pass the value to the `RRule` object. Instead, you give it `$start_date` (in: `$rule = new RRule($events[$e]['event_rrule'],$start_date);`), which is Feb 22 according to your comment, and that's what the lib is calculating. The `RRule` object cannot guess what is the `first_possible_date` if you don't pass it in the constructor.

Also side note: if you want to know *which* event exactly is valid you might not want to use `RSet`. `RSet` will only return the occurrences (the dates) but not what event they correspond to.

**Comment by pluk77** [comment]
@compumatter Thank you so much! Glad I could be of assistance.

**Comment by compumatter** [comment]
OK, solved.  The last problem was I was using the range of events 'start_date' instead of the event itself start_date.  

I also found as you pointed out Remi that using rset was not the way to go.  

I am so happy :-) 

Thank you so much for creating this rrule processing code.  It is so needed and saved me a ton of work - if I was even up to the task ;-)

I'm attaching a zipped php file which though geared to my particular fields and nomenclature will provide a working model that others can pull from and improve upon.

Thanks again.

Jay Lepore
CompuMatter

[index.zip](https://github.com/rlanvin/php-rrule/files/4269482/index.zip)

**Comment by rlanvin** [comment]
You are welcome, I'm glad that your problem is now solved. Thank you very much for your contribution.
