### ISSUE TITLE
Catalan i18n php file

### ISSUE THREAD

**Issue by davrr** [rlanvin/php-rrule#80]
Hi.

I'm interested in contributing to create a catalan version of the interpreter.

Sorry if this is not the place to request it, I'm totally new on github.

I have a version already created in my local environment.

Thanks

**Comment by rlanvin** [comment]
Hey, thank you I appreciate your contribution. You'll need to create a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) so I can merge the translation file.

**Comment by rlanvin** [comment]
@davrr Any news on the pull request?
