### ISSUE TITLE
Reusing generated rule throws exception

### ISSUE THREAD

**Issue by twisted1919** [rlanvin/php-rrule#81]
If we use the example given in the docs:
```php
$rrule = new RRule([
    'FREQ' => 'MONTHLY',
    'INTERVAL' => 1,
    'DTSTART' => '2015-06-01',
    'COUNT' => 6
]);
```
We can simply echo `$rrule` since it implements `__toString` and gives us a string frequency like:
`DTSTART:20150601T000000Z RRULE:FREQ=MONTHLY;COUNT=6`

Which i would expect to work just fine if i throw it in the constructor of the `RRule` class:
```php
$rrule = new RRule('DTSTART:20150601T000000Z RRULE:FREQ=MONTHLY;COUNT=6');
```
But this gives an exception `The FREQ rule part must be one of the following: SECONDLY, MINUTELY, HOURLY, DAILY, WEEKLY, MONTHLY, YEARLY` so you have to manually parse the `DTSTART` part and extract it so you can then do:
```php
$rrule = new RRule('RRULE:FREQ=MONTHLY;COUNT=6', '20150601T000000Z');
```
Shouldn't the library handle this by itself?

It's just trivial to change the RRule constructor into something like:
```php
if (is_string($parts)) {
	if (!$dtstart) {
		$pattern = '/^DTSTART:([0-9A-Z]+)\s/i';
		if (preg_match($pattern, $parts, $matches) && \DateTime::createFromFormat('Ymd\THis\Z', $matches[1])){
			$dtstart = $matches[1];
			$parts   = (string)preg_replace($pattern, '', $parts);	
		}
	}
	$parts = RfcParser::parseRRule($parts, $dtstart);
	$parts = array_change_key_case($parts, CASE_UPPER);
}
```
Which would handle dtstart automatically and wouldn't break BC at all since the `$dtstart` param would still have priority.

**Comment by rlanvin** [comment]
Hello,

> Shouldn't the library handle this by itself?

It does. The following code works fine:

```
$rrule = new RRule([
    'FREQ' => 'MONTHLY',
    'INTERVAL' => 1,
    'DTSTART' => '2015-06-01',
    'COUNT' => 6
]);

$str = (string) $rrule;

$rrule = new RRule($str);
```

The string constructed by the library contains a `\n` character, to separate `DTSTART` and `RRULE` (this is how the RFC specifies it). The correct string is:

```
DTSTART;TZID=Europe/Berlin:20150601T000000
RRULE:FREQ=MONTHLY;COUNT=6`
```

In your example, you seem to have replaced the `\n` with a space somehow. I would suggest to check where this conversion occurred. If that is the output of the lib, could you tell me what version you are using?

**Comment by twisted1919** [comment]
Thank you for the quick reply in a weekend, i now was reading about the newline character in the rfc and you are right, it works perfectly fine, sorry for reporting a false issue. 
I just copied the string without the newline character, that's the reason.
