### ISSUE TITLE
Weekly rule doesn't parse correctly

### ISSUE THREAD

**Issue by munsterlander** [rlanvin/php-rrule#82]
So given a string rule of:

`FREQ=WEEKLY;BYDAY=WE,TH,FR;INTERVAL=1;COUNT=10;`

The expected result would be 10 weeks with WE,TH,FR having events.  The actual output is 10 occurrences of those days all contained within four weeks, so we get basically:

`WE,TH,FR,WE,TH,FR,WE,TH,FR,WE`

Is the rule malformed or is there an issue within the parser?  We have tried breaking the rule up and using `new RRule()` and passing an associative array of values and get the same results.

Any thoughts on this?

**Comment by pluk77** [comment]
Unfortunately your expectations are incorrect. The COUNT defines the number of times the event should be repeated.

https://icalendar.org/iCalendar-RFC-5545/3-8-6-2-repeat-count.html

If you know the start date, you could use UNTIL to set an end date for 4 weeks later and remove the COUNT parameter.

**Comment by rlanvin** [comment]
I can only confirm what @pluk77 said, unfortunately your expectation _"The expected result would be 10 weeks with WE,TH,FR having events."_ is incorrect, the RFC defines `COUNT` as the number of occurrences.

If you want 10 weeks, you could:
- use `UNTIL` instead, for a date 10 weeks later
- if you know you have 3 occurrences per week, use `COUNT=30`.

**Comment by munsterlander** [comment]
My apologies all, we are using the docs from [here](https://tools.ietf.org/html/rfc5545#page-40) and I guess we misinterpreted these sections:

> FREQ=WEEKLY, to specify repeating events based on an interval of a week or more;
> The INTERVAL rule part contains a positive integer representing at which intervals the recurrence rule repeats.  The default value is "1", meaning every week for a WEEKLY rule. 
> The COUNT rule part defines the number of occurrences at which to range-bound the recurrence. 

We will come up with a way to make sure it is clear to our users.  Thank you for the fast response!
