### ISSUE TITLE
Invalid UNTIL property: if the "DTSTART" property is specified as a date with local time, then the UNTIL rule part MUST also be specified as a date with local time

### ISSUE THREAD

**Issue by twisted1919** [rlanvin/php-rrule#83]
Just got this error for this string: 
 
`DTSTART:20200509T190000Z\nRRULE:FREQ=WEEKLY;INTERVAL=1;WKST=MO;BYDAY=MO;UNTIL=20200801T193000Z`

I tracked it down to RfcParser.php file at line 171:  
```php
case 'localtime':
	if (strpos($value, 'T') === false || strpos($value, 'Z') !== false) {
		throw new \InvalidArgumentException(
			'Invalid UNTIL property: if the "DTSTART" property is specified as a date with local time, then the UNTIL rule part MUST also be specified as a date with local time'
		);
	}
	break;
``` 
It seems the second `strpos` comparison should be made using the `===` operator instead of `!==` ? If i do this, it fixes the issue.

Best.

**Comment by rlanvin** [comment]
Hey can you share a code snippet and the version of the lib you are using? I just tried this rule and it seems to be working for me (the lib calculates that the rule has 12 occurrences).

**Comment by twisted1919** [comment]
Hey,
Thanks for the follow up, i did a composer update and now it seems the issue has went away.
I will close this for now, if i get same error again i'll make sure to give you a sample to help you reproduce it.
