### ISSUE TITLE
How to reset rule set iterator?

### ISSUE THREAD

**Issue by sabat24** [rlanvin/php-rrule#84]
After first foreach like
```php
$i=0;
foreach($rSet as $occurrence) {
    $i++;
    if ($i == 20) {
        break;
    }
}
```

I would like to again iterate rule set object from first occurrence. But after first foreach offset is set to 20th occurrence. 

So following code
```php
$i=0;
foreach($rSet as $occurrence) {
    $i++;
    if ($i == 20) {
        break;
    }
}

$i=0;
foreach($rSet as $occurrence) {
    $i++;
    if ($i == 20) {
        break;
    }
}
```

will generate first 40 occurrences. Which is basically correct. However I would like to rewind iterator after first `foreach`. I tried `getIterator()->rewind()` or `reset($rSet)` but nothing worked.

**Comment by rlanvin** [comment]
I see you closed the ticket so I think you got your answer already. Just for the record, `foreach` rewinds the iterator when the loop start (as explained [in the documentation](https://www.php.net/manual/en/iterator.rewind.php)), so what you are describing isn't possible as far as I can tell. That said, if you closed this ticket by mistake feel free to reopen it.

**Comment by sabat24** [comment]
Yes, it was my mistake. I made some changes inside your core code to customize the library. I forgot to remove some internal reference and this is why I started to receive strange results inside my test cases. After writing that issue I suddenly figured it out.
