### ISSUE TITLE
Setting DTSTART to start for getOccurrencesBetween

### ISSUE THREAD

**Issue by alexandres** [rlanvin/php-rrule#86]
$rrule->getOccurrencesBetween($start, $end) will run through every occurrences since $rrule->dtstart, checking if it is between $start and $end. This is very costly for rules with old dtstarts.

As an optimization, I'm setting $rrule->dtstart to $start. 

Are there any gotchas in doing this?

**Comment by rlanvin** [comment]
>  This is very costly for rules with old dtstarts.

Can you give an example of such rule, and define what "very costly" means for you? I would be curious to try and see what could be optimized.

> Are there any gotchas in doing this?

It will work under most circumstances, and is generally a good solution for very long-lived rule, **as long as $start is an occurrence of the rule**. If $start isn't an occurrence, you'll have issues. For example if you want a rule "every 2 days" and you start on the wrong day, every result will be off by one.

Also UNTIL and COUNT will not work anymore, obviously.

**Comment by alexandres** [comment]
I've put together a little benchamark with highlights the issue:
```php
<?php

use RRule\RRule;
use Carbon\Carbon;

require __DIR__.'/../vendor/autoload.php';

$rules = explode("\n", "DTSTART:20100424T000000|RRULE:FREQ=DAILY;BYHOUR=8,16
DTSTART:20100424T000000|RRULE:FREQ=HOURLY;BYMINUTE=0,15,30,45");
$now = Carbon::now();
foreach ($rules as $rule) {
    echo "RULE: " . $rule . "\n";
    $parts = explode("|", trim($rule));
    foreach ([explode(":", $parts[0])[1], $now->startOfDay()->format('Ymd\THis')] as $dtindex => $dtstart) {
        $times = [];
        $timesCached = [];
        foreach (range(0, 10) as $i) {
            $rrule = new RRule($parts[1], $dtstart);
            $start = microtime(true);
            $rrule->getOccurrencesBetween($now->startOfDay(), $now->endOfDay());
            $times[] = (string)(microtime(true)-$start);
            $start = microtime(true);
            $rrule->getOccurrencesBetween($now->startOfDay(), $now->endOfDay());
            $timesCached[] = (string)(microtime(true)-$start);
        }
        $rrule = new RRule($parts[1], $dtstart);
        $cacheSize = count($rrule->getOccurrencesBetween(RRule::parseDate($dtstart), $now->endOfDay()));
        echo ($dtindex == 0 ? "No DTSTART optimization" : "With optimization ") . ": " .  "uncached=" . array_sum($times)/count($times) . ",cached=" . array_sum($timesCached)/count($timesCached) . ",cachesize=" . $cacheSize . "\n";
    }
}
```

Output:
```
RULE: DTSTART:20100424T000000|RRULE:FREQ=DAILY;BYHOUR=8,16
No DTSTART optimization: uncached=0.046249086206609,cached=0.00552114573392,cachesize=7640
With optimization : uncached=3.5264275290749E-5,cached=5.6136738170277E-6,cachesize=2
RULE: DTSTART:20100424T000000|RRULE:FREQ=HOURLY;BYMINUTE=0,15,30,45
No DTSTART optimization: uncached=1.4678138819608,cached=0.34307319467718,cachesize=366720
With optimization : uncached=0.00039742209694603,cached=7.2349201549183E-5,cachesize=96
```

Without the DTSTART optimization, the HOURLY rule takes over one second, and still takes 0.34 seconds with the cache. Not only is the cache not helping much, but it is also taking a lot of memory (366k DateTime objects in this case). With a sufficient number of RRULEs, memory becomes an issue.

Is there a way to identify a rule which cannot use this optimization?

**Comment by rlanvin** [comment]
Ok I see, so this is exactly what is mentioned in the notes in the Wiki: https://github.com/rlanvin/php-rrule/wiki/RRule#notes

> The current algorithm to compute occurrences is faster at lower frequencies and slower at higher the frequencies. So YEARLY is faster that MONTHLY which is faster than WEEKLY and so on. So if you want to achieve the fastest calculation time, whenever possible, try to use the lowest possible frequency. For example, to get "every day in january" it is slightly faster to write ['freq' => 'yearly','bymonth' => 1,'bymonthday' => range(1,31)] rather than ['freq' => 'daily','bymonth' => 1].
> [...]
> Computing all occurrences of rule might get noticeably slow with very high frequencies (MINUTELY or SECONDELY) if the rule last a long period of time (such as many years).

So yes, definitely computing 4 occurrences per hour for 10 years is going to be slow the first time (but hey, only 1.4s is actually pretty good given the amount of dates :-). This kind of rule also works really well with a different DTSTART, so this would be the right approach in this case.

> Is there a way to identify a rule which cannot use this optimization?

It's a tricky question, and you'll see there is a reason why it actually has to calculate all the occurrences. TL;DR is any rule that is logically independent from the value of DTSTART would work with this optimization.

- **If the rule is infinite, and you use a known occurrence as new dtstart**, then I believe it will work all the time. That's the only case where it's pretty much guaranteed. Basically keep the latest results somewhere in a cache/DB/whatever to pick the calculation where you left of next time. But everything else is super dodgy.
- **If the rule if finite using COUNT** it'll never work - but it's unlikely to run in this case unless you have an insanely high COUNT.
- **If the rule is finite using UNTIL** it might work as long as the new dtstart is before the UNTIL date
- **If the rule uses an interval that is not 1** it'll probably not work, unless the new dtstart is "aligned" with the previous dtstart. For example if you have a rule that is "every 7 days" and the original DTSTART is a Monday, it'll always be a Monday. If you replace dtstart by a date on a Wednesday, then all your results will be Wednesdays.

In RFC 5545, a lot of things are derived from DTSTART to do the calculations of the sequence of occurrences, so it's more or less impossible to predict programmatically if the result would be the same with a different DTSTART - or at least I don't know how (maybe someone smarter than me could provide an algorithm).

**Comment by rlanvin** [comment]
I'm closing this ticket now, but feel free to re-open it if you want to continue the discussion.

**Comment by shahiddgk** [comment]
Hi sir,
I have a confusion about getting result format of rrule.
code used,

`$event = Event::find('4jqma5kvstf6rms9jjmuaq7h9v','portalcalendar3@gmail.com');
$rrule = new RRule($event->recurrence[0]);`

if i return $rrule  its gives:
FREQ=WEEKLY;UNTIL=20210731T185959Z;BYDAY=FR,TH;WKST=SU

while in spatie google calendar event class with find eventId and calendarId then return:
`[recurrence] => Array
                (
                    [0] => RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20210731T185959Z;BYDAY=FR,TH
                )`
so lastly i try to find a way to make like this:
`DTSTART:20191111T103000Z\nRRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20210731T185959Z;BYDAY=FR,TH`

Please help.

**Comment by rlanvin** [comment]
@shahiddgk I'm sorry there isn't enough context in your message. I think you should open the ticket on spatie google calendar project instead.

**Comment by alexandre-le-borgne** [comment]
Thank you for these very interesting answers. I have a few other questions about this situation :  I want to calculate the occurrences of an RRule over time. For this I want to use the proposed optimization (use the date of the last occurrence calculated as a new starting point)

> If the rule is infinite, and you use a known occurrence as new dtstart, then I believe it will work all the time


**1*** 
It doesn't seem obvious to me (especially when using BY*).  Do you know any proof (or source) of this fact?


> If the rule if finite using COUNT it'll never work - but it's unlikely to run in this case unless you have an insanely high COUNT.
In the case where we have a very high COUNT, and we want to calculate the occurrences progressively :

Can't we consider that the COUNT to use is the original COUNT - the index of the last calculated occurrence (we will also use its date as the new dtstart) ?


> If the rule uses an interval that is not 1 it'll probably not work, unless the new dtstart is "aligned" with the previous dtstart. For example if you have a rule that is "every 7 days" and the original DTSTART is a Monday, it'll always be a Monday. If you replace dtstart by a date on a Wednesday, then all your results will be Wednesdays.

If **(1*)** is true, same case as for an infinite rule: There should be no problem if we use the date of a known occurrence ?

**Comment by alexandre-le-borgne** [comment]
Thanks for taking the time to reply

> I don't really a situation where this would not work. Do you have something in mind?

I took an hour to look for a counterexample without success: so much the better.
