### ISSUE TITLE
Determine if two RRule's conflict/overlap in occurrences

### ISSUE THREAD

**Issue by ctwillie** [rlanvin/php-rrule#89]
THIS IS NOT A BUG REPORT. JUST A QUESTION.

I am wanting to know how I would determine if two rules have overlapping occurrences.

Thanks in advance for any help with this!

**Comment by rlanvin** [comment]
If the rules are finite you could always calculate all the occurrences of both rules and just compare the two resultsets. Can you be a bit more specific about you use case?

**Comment by ctwillie** [comment]
I am sorry for being so vague. I was in a rush. But, yes. This is how I am doing it now. I just didn't know if there was a better or more efficient way of calculating overlapping occurrences. Thanks.

Last question, (promise), is how would I go about calculating "gaps" where there are no occurrences for a specified time period.
Example: If two users are on a schedule and both create an RRule and both RRule's are added to the same RSet, how can I make sure every day, minute, hour etc. is "covered" in the schedule. Meaning, there is no gap where an occurrence does not exist. The domain requirement is there can be no gaps in a schedule for the time period it pertains.

Hope I am making some sense here. Thanks again for the help!

**Comment by rlanvin** [comment]
> how can I make sure every day, minute, hour etc. is "covered" in the schedule.

Well that's a strange use case but alright... You could create the "perfect" rule - say, if you want to make sure every hour is covered in a 24-hour schedule, something like `FREQ=HOURLY;COUNT=24` and then compare that the expected resultset is contained inside the RSet resultset.

**Comment by rlanvin** [comment]
Feel free to reopen if you want to continue the conversation.
