### ISSUE TITLE
Finnish translation fix

### ISSUE THREAD

**Issue by tplanner** [rlanvin/php-rrule#94]
Sorry I don't exactly know how to make pull request, but in the file i18n/fi.php in monthly and daily "else" strings there is a need for small fix. There is "count" which I think is supposed to be "interval" like for example in en.php file.

Thank you for the useful repository!

**Comment by rlanvin** [comment]
Hello, I can make the changes myself but I would need to know exactly what you want to change. I don't speak Finnish fluently :-)

**Comment by tplanner** [comment]
Sorry not being precise enough. The translation itself is well made.

File i18n/fi.php:
line 24: 'else' => '%{count} kuukauden välein'   ->   'else' => '%{interval} kuukauden välein'
and
line 34: 'else' => '%{count} päivän välein'   ->   'else' => '%{interval} päivän välein'
